namespace OpenCad2D.Interaction.Snapping;

/// <summary>
/// Defines the available object snap modes.
/// </summary>
[Flags]
public enum SnapKind
{
    None = 0,

    Endpoint = 1,

    Midpoint = 2,

    Center = 4,

    Quadrant = 8,

    Intersection = 16,

    Nearest = 32,

    Perpendicular = 64,

    Tangent = 128,

    Grid = 256,

    /// <summary>
    /// Entity snap used by selection-oriented tools.
    /// It is intentionally excluded from All because All represents geometric snaps.
    /// </summary>
    Entity = 512,

    /// <summary>
    /// Temporary tracking snap generated from smart points.
    /// It is intentionally excluded from All because it is not an object snap persisted in settings.
    /// </summary>
    Tracking = 1024,

    /// <summary>
    /// Temporary snap generated by the intersection of two smart point tracking lines.
    /// It is intentionally excluded from All because it is not an object snap persisted in settings.
    /// </summary>
    TrackingIntersection = 2048,

    /// <summary>
    /// Temporary extension snap generated from the real direction of a linear entity or straight polyline segment.
    /// It is intentionally excluded from All because it is not an object snap persisted in settings.
    /// </summary>
    Extension = 4096,

    /// <summary>
    /// Temporary snap generated directly from a captured smart point.
    /// It is intentionally excluded from All because it is not an object snap persisted in settings.
    /// </summary>
    SmartPoint = 8192,

    /// <summary>
    /// Temporary snap generated when an enabled grid node lies on an active tracking or extension line.
    /// The tracking or extension line remains the dominant constraint; the grid node is used only when it is on that line.
    /// </summary>
    TrackingGridIntersection = 16384,

    /// <summary>
    /// Temporary snap generated when an enabled grid node lies on an active entity extension line.
    /// The extension line remains the dominant constraint; the grid node is used only when it is on that line.
    /// </summary>
    ExtensionGridIntersection = 32768,

    All = Endpoint
        | Midpoint
        | Center
        | Quadrant
        | Intersection
        | Nearest
        | Perpendicular
        | Tangent
        | Grid,

    /// <summary>
    /// Snap set used when the active command needs to pick entities rather than points.
    /// </summary>
    EntityOnly = Entity
}