namespace OpenCad2D.Tools.Common;

/// <summary>
/// Identifies a CAD tool available in the application.
/// </summary>
public enum ToolId
{
    Selection,
    ZoomWindow,
    Point,
    Text,
    MultilineText,
    Line,
    Rectangle,
    RectangleBySides,
    Circle,
    Ellipse,
    Arc,
    ArcThreePoints,
    Polyline,
    Spline,
    Polygon,
    Divide,
    NorthSymbol,
    ScaleBar,
    Stair,
    Door,
    Window,
    HorizontalDimension,
    VerticalDimension,
    AlignedDimension,
    RadiusDimension,
    DiameterDimension,
    AngularDimension,
    Move,
    Copy,
    Rotate,
    Scale,
    Align,
    BreakAtPoint,
    BreakBetweenPoints,
    Extend,
    Trim,
    Offset,
    BoundaryFill,
    Fillet,
    Chamfer,
    Mirror,
    Explode,
    Join,
    Delete,
    MeasureDistance,
    MeasureEntity,
    MeasureAngle,
    MeasureArea
}
