using System.Globalization;
using System.Text;
using System.Xml;
using OpenCad2D.Core.Documents;
using OpenCad2D.Core.Entities;
using OpenCad2D.Core.Layers;
using OpenCad2D.Core.Styling;
using OpenCad2D.Geometry.Primitives;

namespace OpenCad2D.Export.Svg;

/// <summary>
/// Exports CAD documents to a simple internal SVG representation.
/// </summary>
public sealed class SvgExporter : ISvgExporter
{
    private const double EmptyDocumentSize = 100.0;

    public SvgExportResult Export(
        CadDocument document,
        SvgExportOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(document);

        SvgExportOptions actualOptions = options ?? SvgExportOptions.Default;
        double margin = Math.Max(0, actualOptions.Margin);

        IReadOnlyList<CadEntity> entities = GetExportableEntities(
            document,
            actualOptions)
            .ToList();

        BoundingBox2D? contentBounds = GetContentBounds(entities);

        double width;
        double height;

        if (contentBounds is null)
        {
            width = EmptyDocumentSize + margin * 2.0;
            height = EmptyDocumentSize + margin * 2.0;
        }
        else
        {
            width = Math.Max(1.0, contentBounds.Value.Width + margin * 2.0);
            height = Math.Max(1.0, contentBounds.Value.Height + margin * 2.0);
        }

        var builder = new StringBuilder();

        builder.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
        builder.AppendLine($"<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 {Format(width)} {Format(height)}\" width=\"{Format(width)}\" height=\"{Format(height)}\">");

        if (actualOptions.IncludeMetadata)
        {
            builder.AppendLine($"  <title>{Escape(actualOptions.Title)}</title>");
            builder.AppendLine("  <desc>Generated by OpenCad2D SVG exporter.</desc>");
        }

        if (actualOptions.IncludeBackground)
        {
            builder.AppendLine($"  <rect x=\"0\" y=\"0\" width=\"{Format(width)}\" height=\"{Format(height)}\" fill=\"{Escape(actualOptions.BackgroundColor)}\" />");
        }

        foreach (CadEntity entity in entities)
        {
            Layer layer = document.Layers.GetRequired(entity.LayerId);
            LineFormat lineFormat = ResolveLineFormat(
                document,
                layer);

            string? svgElement = ExportEntity(
                entity,
                lineFormat,
                contentBounds,
                width,
                height,
                margin);

            if (!string.IsNullOrWhiteSpace(svgElement))
            {
                builder.AppendLine(svgElement);
            }
        }

        builder.AppendLine("</svg>");

        return new SvgExportResult(
            builder.ToString(),
            entities.Count,
            contentBounds,
            width,
            height);
    }

    public void ExportToFile(
        CadDocument document,
        string filePath,
        SvgExportOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(document);

        if (string.IsNullOrWhiteSpace(filePath))
        {
            throw new ArgumentException(
                "SVG export file path cannot be empty.",
                nameof(filePath));
        }

        SvgExportResult result = Export(
            document,
            options);

        string? directory = Path.GetDirectoryName(filePath);

        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(
            filePath,
            result.Content,
            Encoding.UTF8);
    }

    private static IEnumerable<CadEntity> GetExportableEntities(
        CadDocument document,
        SvgExportOptions options)
    {
        IEnumerable<CadEntity> entities = options.IncludeHiddenLayers
            ? document.Entities.All.Where(entity => entity.IsVisible)
            : document.GetVisibleEntities();

        return entities
            .OrderBy(entity => document.Layers.GetRequired(entity.LayerId).Name, StringComparer.OrdinalIgnoreCase)
            .ThenBy(entity => entity.DrawOrder);
    }

    private static BoundingBox2D? GetContentBounds(
        IReadOnlyList<CadEntity> entities)
    {
        if (entities.Count == 0)
        {
            return null;
        }

        BoundingBox2D first = entities[0].GetBoundingBox();

        double minX = first.MinX;
        double minY = first.MinY;
        double maxX = first.MaxX;
        double maxY = first.MaxY;

        foreach (CadEntity entity in entities.Skip(1))
        {
            BoundingBox2D bounds = entity.GetBoundingBox();

            minX = Math.Min(minX, bounds.MinX);
            minY = Math.Min(minY, bounds.MinY);
            maxX = Math.Max(maxX, bounds.MaxX);
            maxY = Math.Max(maxY, bounds.MaxY);
        }

        return new BoundingBox2D(
            minX,
            minY,
            maxX,
            maxY);
    }

    private static string? ExportEntity(
        CadEntity entity,
        LineFormat lineFormat,
        BoundingBox2D? contentBounds,
        double width,
        double height,
        double margin)
    {
        if (contentBounds is null)
        {
            return null;
        }

        return entity switch
        {
            LineEntity line => ExportLine(
                line,
                lineFormat,
                contentBounds.Value,
                height,
                margin),

            CircleEntity circle => ExportCircle(
                circle,
                lineFormat,
                contentBounds.Value,
                height,
                margin),

            PolylineEntity polyline => ExportPolyline(
                polyline,
                lineFormat,
                contentBounds.Value,
                height,
                margin),

            ArcEntity arc => ExportArc(
                arc,
                lineFormat,
                contentBounds.Value,
                height,
                margin),

            _ => null
        };
    }

    private static string ExportLine(
        LineEntity line,
        LineFormat lineFormat,
        BoundingBox2D bounds,
        double svgHeight,
        double margin)
    {
        Point2D start = ToSvgPoint(
            line.Start,
            bounds,
            svgHeight,
            margin);

        Point2D end = ToSvgPoint(
            line.End,
            bounds,
            svgHeight,
            margin);

        return $"  <line x1=\"{Format(start.X)}\" y1=\"{Format(start.Y)}\" x2=\"{Format(end.X)}\" y2=\"{Format(end.Y)}\" {StrokeAttributes(lineFormat)} />";
    }

    private static string ExportCircle(
        CircleEntity circle,
        LineFormat lineFormat,
        BoundingBox2D bounds,
        double svgHeight,
        double margin)
    {
        Point2D center = ToSvgPoint(
            circle.Center,
            bounds,
            svgHeight,
            margin);

        return $"  <circle cx=\"{Format(center.X)}\" cy=\"{Format(center.Y)}\" r=\"{Format(circle.Radius)}\" {StrokeAttributes(lineFormat)} />";
    }

    private static string ExportPolyline(
        PolylineEntity polyline,
        LineFormat lineFormat,
        BoundingBox2D bounds,
        double svgHeight,
        double margin)
    {
        string points = string.Join(
            " ",
            polyline.Vertices.Select(vertex =>
            {
                Point2D svgPoint = ToSvgPoint(
                    vertex,
                    bounds,
                    svgHeight,
                    margin);

                return $"{Format(svgPoint.X)},{Format(svgPoint.Y)}";
            }));

        string tagName = polyline.IsClosed
            ? "polygon"
            : "polyline";

        return $"  <{tagName} points=\"{points}\" {StrokeAttributes(lineFormat)} />";
    }

    private static string ExportArc(
        ArcEntity arc,
        LineFormat lineFormat,
        BoundingBox2D bounds,
        double svgHeight,
        double margin)
    {
        Point2D start = ToSvgPoint(
            arc.Geometry.StartPoint,
            bounds,
            svgHeight,
            margin);

        Point2D end = ToSvgPoint(
            arc.Geometry.EndPoint,
            bounds,
            svgHeight,
            margin);

        double delta = GetPositiveSweepRadians(
            arc.StartAngle.Radians,
            arc.EndAngle.Radians,
            arc.IsCounterClockwise);

        int largeArcFlag = delta > Math.PI
            ? 1
            : 0;

        int sweepFlag = arc.IsCounterClockwise
            ? 1
            : 0;

        return $"  <path d=\"M {Format(start.X)} {Format(start.Y)} A {Format(arc.Radius)} {Format(arc.Radius)} 0 {largeArcFlag} {sweepFlag} {Format(end.X)} {Format(end.Y)}\" {StrokeAttributes(lineFormat)} />";
    }

    private static double GetPositiveSweepRadians(
        double startRadians,
        double endRadians,
        bool isCounterClockwise)
    {
        double delta = isCounterClockwise
            ? endRadians - startRadians
            : startRadians - endRadians;

        delta %= 2.0 * Math.PI;

        if (delta < 0)
        {
            delta += 2.0 * Math.PI;
        }

        return delta;
    }

    private static Point2D ToSvgPoint(
        Point2D point,
        BoundingBox2D bounds,
        double svgHeight,
        double margin)
    {
        double x = point.X - bounds.MinX + margin;
        double y = point.Y - bounds.MinY + margin;

        return new Point2D(
            x,
            y);
    }

    private static LineFormat ResolveLineFormat(
        CadDocument document,
        Layer layer)
    {
        if (document.LineFormats.TryGetById(
            layer.LineFormatId,
            out LineFormat? lineFormat) &&
            lineFormat is not null)
        {
            return lineFormat;
        }

        return LineFormatCollection.Default.GetById(LineFormatCollection.Default.All[0].Id);
    }

    private static string StrokeAttributes(LineFormat lineFormat)
    {
        var attributes = new StringBuilder();

        attributes.Append($"stroke=\"{ToHex(lineFormat.Color)}\" ");
        attributes.Append($"stroke-width=\"{Format(lineFormat.LineWeight.Millimeters)}\" ");
        attributes.Append("fill=\"none\" vector-effect=\"non-scaling-stroke\"");

        double[]? dashPattern = LineStyleDashPattern.Get(lineFormat.LineStyle);

        if (dashPattern is not null && dashPattern.Length > 0)
        {
            attributes.Append($" stroke-dasharray=\"{FormatDashArray(dashPattern)}\"");
        }

        return attributes.ToString();
    }

    private static string FormatDashArray(IEnumerable<double> values)
    {
        return string.Join(
            " ",
            values.Select(Format));
    }

    private static string ToHex(CadColor color)
    {
        return $"#{color.R:X2}{color.G:X2}{color.B:X2}";
    }

    private static string Format(double value)
    {
        return value.ToString(
            "0.###",
            CultureInfo.InvariantCulture);
    }

    private static string Escape(string value)
    {
        return XmlConvert.EncodeName(value) == value
            ? System.Security.SecurityElement.Escape(value) ?? string.Empty
            : System.Security.SecurityElement.Escape(value) ?? string.Empty;
    }
}
