using System.Globalization;
using System.Text;
using System.Xml;
using OpenCad2D.Core.Dimensions;
using OpenCad2D.Core.Dimensions.Rendering;
using OpenCad2D.Core.Documents;
using OpenCad2D.Core.Entities;
using OpenCad2D.Core.Identifiers;
using OpenCad2D.Core.Layers;
using OpenCad2D.Core.Styling;
using OpenCad2D.Geometry.Primitives;

namespace OpenCad2D.Export.Svg;

/// <summary>
/// Exports CAD documents to a simple internal SVG representation.
/// </summary>
public sealed class SvgExporter : ISvgExporter
{
    private const double EmptyDocumentSize = 100.0;

    public SvgExportResult Export(
        CadDocument document,
        SvgExportOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(document);

        SvgExportOptions actualOptions = options ?? SvgExportOptions.Default;
        double margin = Math.Max(0, actualOptions.Margin);

        IReadOnlyList<CadEntity> entities = GetExportableEntities(
            document,
            actualOptions)
            .ToList();

        BoundingBox2D? contentBounds = GetContentBounds(
            document,
            entities);

        double width;
        double height;

        if (contentBounds is null)
        {
            width = EmptyDocumentSize + margin * 2.0;
            height = EmptyDocumentSize + margin * 2.0;
        }
        else
        {
            width = Math.Max(1.0, contentBounds.Value.Width + margin * 2.0);
            height = Math.Max(1.0, contentBounds.Value.Height + margin * 2.0);
        }

        var builder = new StringBuilder();

        builder.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
        builder.AppendLine($"<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 {Format(width)} {Format(height)}\" width=\"{Format(width)}\" height=\"{Format(height)}\">");

        if (actualOptions.IncludeMetadata)
        {
            builder.AppendLine($"  <title>{Escape(actualOptions.Title)}</title>");
            builder.AppendLine("  <desc>Generated by OpenCad2D SVG exporter.</desc>");
        }

        string? backgroundColor = ResolveBackgroundColor(actualOptions);

        if (!string.IsNullOrWhiteSpace(backgroundColor))
        {
            builder.AppendLine($"  <rect x=\"0\" y=\"0\" width=\"{Format(width)}\" height=\"{Format(height)}\" fill=\"{Escape(backgroundColor)}\" />");
        }

        if (actualOptions.GroupByLayer)
        {
            AppendEntitiesGroupedByLayer(
                builder,
                document,
                entities,
                contentBounds,
                width,
                height,
                margin);
        }
        else
        {
            foreach (CadEntity entity in entities)
            {
                Layer layer = document.Layers.GetRequired(entity.LayerId);
                LineFormat lineFormat = ResolveLineFormat(
                    document,
                    layer);

                string? svgElement = ExportEntity(
                    document,
                    entity,
                    lineFormat,
                    contentBounds,
                    width,
                    height,
                    margin);

                if (!string.IsNullOrWhiteSpace(svgElement))
                {
                    builder.AppendLine(svgElement);
                }
            }
        }

        builder.AppendLine("</svg>");

        return new SvgExportResult(
            builder.ToString(),
            entities.Count,
            contentBounds,
            width,
            height);
    }

    public void ExportToFile(
        CadDocument document,
        string filePath,
        SvgExportOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(document);

        if (string.IsNullOrWhiteSpace(filePath))
        {
            throw new ArgumentException(
                "SVG export file path cannot be empty.",
                nameof(filePath));
        }

        SvgExportResult result = Export(
            document,
            options);

        string? directory = Path.GetDirectoryName(filePath);

        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(
            filePath,
            result.Content,
            Encoding.UTF8);
    }

    private static string? ResolveBackgroundColor(SvgExportOptions options)
    {
        if (!options.IncludeBackground ||
            options.BackgroundMode == SvgBackgroundMode.Transparent)
        {
            return null;
        }

        return options.BackgroundMode switch
        {
            SvgBackgroundMode.White => "#FFFFFF",
            _ => options.BackgroundColor
        };
    }

    private static void AppendEntitiesGroupedByLayer(
        StringBuilder builder,
        CadDocument document,
        IReadOnlyList<CadEntity> entities,
        BoundingBox2D? contentBounds,
        double width,
        double height,
        double margin)
    {
        foreach (IGrouping<LayerId, CadEntity> layerGroup in entities.GroupBy(entity => entity.LayerId))
        {
            Layer layer = document.Layers.GetRequired(layerGroup.Key);
            LineFormat lineFormat = ResolveLineFormat(
                document,
                layer);

            builder.AppendLine($"  <g id=\"{Escape(CreateLayerGroupId(layer.Name))}\" data-layer-name=\"{Escape(layer.Name)}\">");

            foreach (CadEntity entity in layerGroup.OrderBy(entity => entity.DrawOrder))
            {
                string? svgElement = ExportEntity(
                    document,
                    entity,
                    lineFormat,
                    contentBounds,
                    width,
                    height,
                    margin);

                if (!string.IsNullOrWhiteSpace(svgElement))
                {
                    builder.AppendLine(IndentSvgElement(svgElement));
                }
            }

            builder.AppendLine("  </g>");
        }
    }

    private static string CreateLayerGroupId(string layerName)
    {
        string encodedName = XmlConvert.EncodeName(layerName);

        return $"layer-{encodedName}";
    }

    private static string IndentSvgElement(string svgElement)
    {
        string normalized = svgElement.TrimEnd();
        string[] lines = normalized.Split(
            new[] { "\r\n", "\n" },
            StringSplitOptions.None);

        return string.Join(
            Environment.NewLine,
            lines.Select(line => "  " + line));
    }

    private static IEnumerable<CadEntity> GetExportableEntities(
        CadDocument document,
        SvgExportOptions options)
    {
        IEnumerable<CadEntity> entities = options.IncludeHiddenLayers
            ? document.Entities.All.Where(entity => entity.IsVisible)
            : document.GetVisibleEntities();

        return entities
            .OrderBy(entity => document.Layers.GetRequired(entity.LayerId).Name, StringComparer.OrdinalIgnoreCase)
            .ThenBy(entity => entity.DrawOrder);
    }

    private static BoundingBox2D? GetContentBounds(
        CadDocument document,
        IReadOnlyList<CadEntity> entities)
    {
        if (entities.Count == 0)
        {
            return null;
        }

        BoundingBox2D first = GetExportBounds(
            document,
            entities[0]);

        double minX = first.MinX;
        double minY = first.MinY;
        double maxX = first.MaxX;
        double maxY = first.MaxY;

        foreach (CadEntity entity in entities.Skip(1))
        {
            BoundingBox2D bounds = GetExportBounds(
                document,
                entity);

            minX = Math.Min(minX, bounds.MinX);
            minY = Math.Min(minY, bounds.MinY);
            maxX = Math.Max(maxX, bounds.MaxX);
            maxY = Math.Max(maxY, bounds.MaxY);
        }

        return new BoundingBox2D(
            minX,
            minY,
            maxX,
            maxY);
    }

    private static BoundingBox2D GetExportBounds(
        CadDocument document,
        CadEntity entity)
    {
        if (entity is DimensionEntity dimension)
        {
            DimensionStyle style = ResolveDimensionStyle(
                document,
                dimension);

            return new DimensionGeometryBuilder()
                .Build(
                    dimension,
                    style)
                .Bounds;
        }

        return entity.GetBoundingBox();
    }

    private static string? ExportEntity(
        CadDocument document,
        CadEntity entity,
        LineFormat lineFormat,
        BoundingBox2D? contentBounds,
        double width,
        double height,
        double margin)
    {
        if (contentBounds is null)
        {
            return null;
        }

        return entity switch
        {
            PointEntity point => ExportPoint(
                point,
                lineFormat,
                contentBounds.Value,
                height,
                margin),

            TextEntity text => ExportText(
                document,
                text,
                contentBounds.Value,
                height,
                margin),

            LinearDimensionEntity linearDimension => ExportDimension(
                document,
                linearDimension,
                lineFormat,
                contentBounds.Value,
                height,
                margin),

            AlignedDimensionEntity alignedDimension => ExportDimension(
                document,
                alignedDimension,
                lineFormat,
                contentBounds.Value,
                height,
                margin),

            RadiusDimensionEntity radiusDimension => ExportDimension(
                document,
                radiusDimension,
                lineFormat,
                contentBounds.Value,
                height,
                margin),

            DiameterDimensionEntity diameterDimension => ExportDimension(
                document,
                diameterDimension,
                lineFormat,
                contentBounds.Value,
                height,
                margin),

            AngularDimensionEntity angularDimension => ExportDimension(
                document,
                angularDimension,
                lineFormat,
                contentBounds.Value,
                height,
                margin),

            LineEntity line => ExportLine(
                line,
                lineFormat,
                contentBounds.Value,
                height,
                margin),

            CircleEntity circle => ExportCircle(
                circle,
                lineFormat,
                contentBounds.Value,
                height,
                margin),

            PolylineEntity polyline => ExportPolyline(
                polyline,
                lineFormat,
                contentBounds.Value,
                height,
                margin),

            ArcEntity arc => ExportArc(
                arc,
                lineFormat,
                contentBounds.Value,
                height,
                margin),

            _ => null
        };
    }


    private static string ExportDimension(
        CadDocument document,
        DimensionEntity dimension,
        LineFormat lineFormat,
        BoundingBox2D bounds,
        double svgHeight,
        double margin)
    {
        DimensionStyle style = ResolveDimensionStyle(
            document,
            dimension);
        TextFormat textFormat = ResolveDimensionTextFormat(
            document,
            style);
        DimensionRenderModel model = new DimensionGeometryBuilder().Build(
            dimension,
            style);

        var builder = new StringBuilder();

        foreach (DimensionLinePrimitive line in model.Lines.Concat(model.Arrows))
        {
            Point2D start = ToSvgPoint(
                line.Start,
                bounds,
                svgHeight,
                margin);
            Point2D end = ToSvgPoint(
                line.End,
                bounds,
                svgHeight,
                margin);

            builder.AppendLine($"  <line x1=\"{Format(start.X)}\" y1=\"{Format(start.Y)}\" x2=\"{Format(end.X)}\" y2=\"{Format(end.Y)}\" {StrokeAttributes(lineFormat)} />");
        }

        foreach (DimensionArcPrimitive arc in model.Arcs)
        {
            builder.AppendLine(ExportDimensionArc(
                arc,
                lineFormat,
                bounds,
                svgHeight,
                margin));
        }

        Point2D textPoint = ToSvgPoint(
            model.Text.Position,
            bounds,
            svgHeight,
            margin);
        double svgRotation = -model.Text.RotationDegrees;
        string fontWeight = textFormat.IsBold ? "bold" : "normal";
        string fontStyle = textFormat.IsItalic ? "italic" : "normal";

        builder.Append($"  <text x=\"{Format(textPoint.X)}\" y=\"{Format(textPoint.Y)}\" font-family=\"{Escape(textFormat.FontFamily)}\" font-size=\"{Format(textFormat.Height)}\" font-weight=\"{fontWeight}\" font-style=\"{fontStyle}\" fill=\"{ToHex(textFormat.Color)}\" transform=\"rotate({Format(svgRotation)} {Format(textPoint.X)} {Format(textPoint.Y)})\">{Escape(model.Text.Text)}</text>");

        return builder.ToString().TrimEnd();
    }

    private static string ExportDimensionArc(
        DimensionArcPrimitive arc,
        LineFormat lineFormat,
        BoundingBox2D bounds,
        double svgHeight,
        double margin)
    {
        Point2D start = ToSvgPoint(
            arc.StartPoint,
            bounds,
            svgHeight,
            margin);
        Point2D end = ToSvgPoint(
            arc.EndPoint,
            bounds,
            svgHeight,
            margin);

        double delta = GetPositiveSweepRadians(
            arc.StartAngleDegrees * Math.PI / 180.0,
            arc.EndAngleDegrees * Math.PI / 180.0,
            arc.IsCounterClockwise);

        int largeArcFlag = delta > Math.PI
            ? 1
            : 0;

        int sweepFlag = arc.IsCounterClockwise
            ? 1
            : 0;

        return $"  <path d=\"M {Format(start.X)} {Format(start.Y)} A {Format(arc.Radius)} {Format(arc.Radius)} 0 {largeArcFlag} {sweepFlag} {Format(end.X)} {Format(end.Y)}\" {StrokeAttributes(lineFormat)} />";
    }

    private static string ExportText(
        CadDocument document,
        TextEntity text,
        BoundingBox2D bounds,
        double svgHeight,
        double margin)
    {
        TextFormat format = ResolveTextFormat(
            document,
            text);

        Point2D point = ToSvgPoint(
            text.InsertionPoint,
            bounds,
            svgHeight,
            margin);

        double svgRotation = -text.RotationDegrees;
        string fontWeight = format.IsBold ? "bold" : "normal";
        string fontStyle = format.IsItalic ? "italic" : "normal";

        return $"  <text x=\"{Format(point.X)}\" y=\"{Format(point.Y)}\" font-family=\"{Escape(format.FontFamily)}\" font-size=\"{Format(format.Height)}\" font-weight=\"{fontWeight}\" font-style=\"{fontStyle}\" fill=\"{ToHex(format.Color)}\" transform=\"rotate({Format(svgRotation)} {Format(point.X)} {Format(point.Y)})\">{Escape(text.Text)}</text>";
    }

    private static string ExportPoint(
        PointEntity point,
        LineFormat lineFormat,
        BoundingBox2D bounds,
        double svgHeight,
        double margin)
    {
        Point2D center = ToSvgPoint(
            point.Position,
            bounds,
            svgHeight,
            margin);

        const double radius = 2.0;

        return $"  <circle cx=\"{Format(center.X)}\" cy=\"{Format(center.Y)}\" r=\"{Format(radius)}\" {StrokeAttributes(lineFormat)} />";
    }

    private static string ExportLine(
        LineEntity line,
        LineFormat lineFormat,
        BoundingBox2D bounds,
        double svgHeight,
        double margin)
    {
        Point2D start = ToSvgPoint(
            line.Start,
            bounds,
            svgHeight,
            margin);

        Point2D end = ToSvgPoint(
            line.End,
            bounds,
            svgHeight,
            margin);

        return $"  <line x1=\"{Format(start.X)}\" y1=\"{Format(start.Y)}\" x2=\"{Format(end.X)}\" y2=\"{Format(end.Y)}\" {StrokeAttributes(lineFormat)} />";
    }

    private static string ExportCircle(
        CircleEntity circle,
        LineFormat lineFormat,
        BoundingBox2D bounds,
        double svgHeight,
        double margin)
    {
        Point2D center = ToSvgPoint(
            circle.Center,
            bounds,
            svgHeight,
            margin);

        return $"  <circle cx=\"{Format(center.X)}\" cy=\"{Format(center.Y)}\" r=\"{Format(circle.Radius)}\" {StrokeAttributes(lineFormat)} />";
    }

    private static string ExportPolyline(
        PolylineEntity polyline,
        LineFormat lineFormat,
        BoundingBox2D bounds,
        double svgHeight,
        double margin)
    {
        string points = string.Join(
            " ",
            polyline.Vertices.Select(vertex =>
            {
                Point2D svgPoint = ToSvgPoint(
                    vertex,
                    bounds,
                    svgHeight,
                    margin);

                return $"{Format(svgPoint.X)},{Format(svgPoint.Y)}";
            }));

        string tagName = polyline.IsClosed
            ? "polygon"
            : "polyline";

        return $"  <{tagName} points=\"{points}\" {StrokeAttributes(lineFormat)} />";
    }

    private static string ExportArc(
        ArcEntity arc,
        LineFormat lineFormat,
        BoundingBox2D bounds,
        double svgHeight,
        double margin)
    {
        Point2D start = ToSvgPoint(
            arc.Geometry.StartPoint,
            bounds,
            svgHeight,
            margin);

        Point2D end = ToSvgPoint(
            arc.Geometry.EndPoint,
            bounds,
            svgHeight,
            margin);

        double delta = GetPositiveSweepRadians(
            arc.StartAngle.Radians,
            arc.EndAngle.Radians,
            arc.IsCounterClockwise);

        int largeArcFlag = delta > Math.PI
            ? 1
            : 0;

        int sweepFlag = arc.IsCounterClockwise
            ? 1
            : 0;

        return $"  <path d=\"M {Format(start.X)} {Format(start.Y)} A {Format(arc.Radius)} {Format(arc.Radius)} 0 {largeArcFlag} {sweepFlag} {Format(end.X)} {Format(end.Y)}\" {StrokeAttributes(lineFormat)} />";
    }

    private static double GetPositiveSweepRadians(
        double startRadians,
        double endRadians,
        bool isCounterClockwise)
    {
        double delta = isCounterClockwise
            ? endRadians - startRadians
            : startRadians - endRadians;

        delta %= 2.0 * Math.PI;

        if (delta < 0)
        {
            delta += 2.0 * Math.PI;
        }

        return delta;
    }

    private static Point2D ToSvgPoint(
        Point2D point,
        BoundingBox2D bounds,
        double svgHeight,
        double margin)
    {
        double x = point.X - bounds.MinX + margin;
        double y = point.Y - bounds.MinY + margin;

        return new Point2D(
            x,
            y);
    }

    private static DimensionStyle ResolveDimensionStyle(
        CadDocument document,
        DimensionEntity dimension)
    {
        if (document.DimensionStyles.TryGetById(
                dimension.DimensionStyleId,
                out DimensionStyle? style) &&
            style is not null)
        {
            return style;
        }

        return document.DimensionStyles.GetById(DimensionStyleId.Standard);
    }

    private static TextFormat ResolveDimensionTextFormat(
        CadDocument document,
        DimensionStyle style)
    {
        if (document.TextFormats.TryGetById(
                style.TextFormatId,
                out TextFormat? format) &&
            format is not null)
        {
            return format;
        }

        return document.TextFormats.GetById(TextFormatId.Annotation);
    }

    private static TextFormat ResolveTextFormat(
        CadDocument document,
        TextEntity text)
    {
        if (document.TextFormats.TryGetById(
                text.TextFormatId,
                out TextFormat? format) &&
            format is not null)
        {
            return format;
        }

        return document.TextFormats.GetById(TextFormatId.Standard);
    }

    private static LineFormat ResolveLineFormat(
        CadDocument document,
        Layer layer)
    {
        if (document.LineFormats.TryGetById(
            layer.LineFormatId,
            out LineFormat? lineFormat) &&
            lineFormat is not null)
        {
            return lineFormat;
        }

        return LineFormatCollection.Default.GetById(LineFormatCollection.Default.All[0].Id);
    }

    private static string StrokeAttributes(LineFormat lineFormat)
    {
        var attributes = new StringBuilder();

        attributes.Append($"stroke=\"{ToHex(lineFormat.Color)}\" ");
        attributes.Append($"stroke-width=\"{Format(lineFormat.LineWeight.Millimeters)}\" ");
        attributes.Append("fill=\"none\" vector-effect=\"non-scaling-stroke\"");

        double[]? dashPattern = LineStyleDashPattern.Get(lineFormat.LineStyle);

        if (dashPattern is not null && dashPattern.Length > 0)
        {
            attributes.Append($" stroke-dasharray=\"{FormatDashArray(dashPattern)}\"");
        }

        return attributes.ToString();
    }

    private static string FormatDashArray(IEnumerable<double> values)
    {
        return string.Join(
            " ",
            values.Select(Format));
    }

    private static string ToHex(CadColor color)
    {
        return $"#{color.R:X2}{color.G:X2}{color.B:X2}";
    }

    private static string Format(double value)
    {
        return value.ToString(
            "0.###",
            CultureInfo.InvariantCulture);
    }

    private static string Escape(string value)
    {
        return XmlConvert.EncodeName(value) == value
            ? System.Security.SecurityElement.Escape(value) ?? string.Empty
            : System.Security.SecurityElement.Escape(value) ?? string.Empty;
    }
}
